/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-12-05 13:46:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class playlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/../include/tail.jsp", Long.valueOf(1670203172927L));
    _jspx_dependants.put("/../include/head.jsp", Long.valueOf(1670203172926L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"EUC-KR\">\r\n");
      out.write("		<title>음악추천</title>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\" integrity=\"sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("		<script src=\"./js/jquery-3.6.0.js\"></script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("	<script>\r\n");
      out.write("	window.onload = function()\r\n");
      out.write("	{\r\n");
      out.write("		$(\"#btn_login\").click(function(){\r\n");
      out.write("			OpenWindow(500, 400, \"login.jsp\", \"로그인\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#btn_join\").click(function(){\r\n");
      out.write("			OpenWindow(500, 550, \"join.jsp\", \"회원가입\");\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	//팝업창 원하는 크기로 화면 중앙에 띄워주는 함수.\r\n");
      out.write("	function OpenWindow(width, height, url, pop_name)\r\n");
      out.write("	{\r\n");
      out.write("		var _width = width;\r\n");
      out.write("		var _height = height;\r\n");
      out.write("		 \r\n");
      out.write("		// 팝업을 가운데 위치시키기 위해 아래와 같이 값 구하기\r\n");
      out.write("		var _left = Math.ceil(( window.screen.width - _width )/2);\r\n");
      out.write("		var _top = Math.ceil(( window.screen.height - _height )/2);\r\n");
      out.write("		window.open(url, pop_name, 'width='+ _width +', height='+ _height +', left=' + _left + ', top='+ _top );\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("		<div class=\"header\">\r\n");
      out.write("			<div class=\"logo\">\r\n");
      out.write("				<a href=\"index.jsp\"><img src=\"./img/melon.jpg\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"search-box\">\r\n");
      out.write("				<form action=\"search.jsp\" method=\"post\">\r\n");
      out.write("				  <input class=\"search-txt\" type=\"text\" placeholder=\"검색어를 입력해 주세요.\">\r\n");
      out.write("				  <a href=\"search.jsp\" class=\"search-btn\">\r\n");
      out.write("				  	 <i class=\"fas fa-search\"></i>\r\n");
      out.write("				  </a>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"login\">\r\n");
      out.write("				<button id=\"btn_login\">로그인</button>	\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"join\">\r\n");
      out.write("				<button id=\"btn_join\">회원가입</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"category\"> \r\n");
      out.write("				<div style=\"float:left;\"><h2><a href=\"musiclist.jsp\" class=\"cate1\">노래 목록 </a></h2></div>\r\n");
      out.write("				<div style=\"float:left; padding-left:20px; padding-right:20px;\"><h2><a href=\"playlist.jsp\" class=\"cate1\">&nbsp;플레이 리스트 </a></h2></div>\r\n");
      out.write("				<div style=\"float:left;\"><h2><a href=\"mytaste.jsp\" class=\"cate1\">&nbsp;내 취향 분석</a></h2></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	window.onload = function()\r\n");
      out.write("	{\r\n");
      out.write("		$(\"#btn_upload\").click(function(){\r\n");
      out.write("			OpenWindow(500, 550, \"upload_playlist.jsp\", \"플레이리스트 업로드\");\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("	</script>	\r\n");
      out.write("		<div class=\"listbody\">\r\n");
      out.write("			<hr>\r\n");
      out.write("				<div class=\"list\">\r\n");
      out.write("					<div style=\"position: relative;\"><a href=\"#\" class=\"hover\" id=\"btn_upload\"><b>플레이리스트 올리기</b></a></div>\r\n");
      out.write("					<div class=\"playlist\">\r\n");
      out.write("						<a href=\"playlistinfo.jsp\"><img src=\"./img/imsi_img.jpg\" style=\"width: 220px; height: 250px;\">\r\n");
      out.write("						</a><div class=\"genre\"><a href=\"platlistinfo.jsp\">오늘같이 싱그러운 날엔?<br></a>인디/어쿠스틱</div></div>\r\n");
      out.write("					<div class=\"playlist\">\r\n");
      out.write("						<a href=\"playlistinfo.jsp\"><img src=\"./img/imsi_img.jpg\" style=\"width: 220px; height: 250px;\">\r\n");
      out.write("						</a><div class=\"genre\"><a href=\"platlistinfo.jsp\">신나는 케이팝과 함께 자존감 끌어 올↗려↗↗<br></a>댄스/아이돌</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"playlist\">\r\n");
      out.write("						<a href=\"playlistinfo.jsp\"><img src=\"./img/imsi_img.jpg\" style=\"width: 220px; height: 250px;\">\r\n");
      out.write("						</a><div class=\"genre\"><a href=\"platlistinfo.jsp\">마음이 쉬고 싶을 때 듣는 위로의 노래<br></a>어쿠스틱/발라드</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"playlist\">\r\n");
      out.write("						<a href=\"playlistinfo.jsp\"><img src=\"./img/imsi_img.jpg\" style=\"width: 220px; height: 250px;\">\r\n");
      out.write("						</a><div class=\"genre\"><a href=\"platlistinfo.jsp\">운전은 네가 해, 음악은 내가 틀게<br></a>아이돌/힙합</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<br>\r\n");
      out.write("				<div class=\"list\">\r\n");
      out.write("					<div class=\"playlist\">\r\n");
      out.write("						<a href=\"playlistinfo.jsp\"><img src=\"./img/imsi_img.jpg\" style=\"width: 220px; height: 250px;\">\r\n");
      out.write("						</a><div class=\"genre\"><a href=\"platlistinfo.jsp\">오늘같이 싱그러운 날엔?<br></a>인디/어쿠스틱</div></div>\r\n");
      out.write("					<div class=\"playlist\">\r\n");
      out.write("						<a href=\"playlistinfo.jsp\"><img src=\"./img/imsi_img.jpg\" style=\"width: 220px; height: 250px;\">\r\n");
      out.write("						</a><div class=\"genre\"><a href=\"platlistinfo.jsp\">신나는 케이팝과 함께 자존감 끌어 올↗려↗↗<br></a>댄스/아이돌</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"playlist\">\r\n");
      out.write("						<a href=\"playlistinfo.jsp\"><img src=\"./img/imsi_img.jpg\" style=\"width: 220px; height: 250px;\">\r\n");
      out.write("						</a><div class=\"genre\"><a href=\"platlistinfo.jsp\">마음이 쉬고 싶을 때 듣는 위로의 노래<br></a>어쿠스틱/발라드</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"playlist\">\r\n");
      out.write("						<a href=\"playlistinfo.jsp\"><img src=\"./img/imsi_img.jpg\" style=\"width: 220px; height: 250px;\">\r\n");
      out.write("						</a><div class=\"genre\"><a href=\"platlistinfo.jsp\">운전은 네가 해, 음악은 내가 틀게<br></a>아이돌/힙합</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("		</div>\r\n");
      out.write("			<div class=\"page\">\r\n");
      out.write("				<a href=\"#\" class=\"pageno\">이전 페이지</a> | \r\n");
      out.write("				<a href=\"#\" class=\"pageno\">1</a> | \r\n");
      out.write("				<a href=\"#\" class=\"pageno\">2</a> | \r\n");
      out.write("				<a href=\"#\" class=\"pageno\">3</a> | \r\n");
      out.write("				<a href=\"#\" class=\"pageno\">4</a> | \r\n");
      out.write("				<a href=\"#\" class=\"pageno\">5</a> | \r\n");
      out.write("				<a href=\"#\" class=\"pageno\">다음 페이지</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("	<hr>\r\n");
      out.write("		명칭: 주식회사 이젠 | 등록번호: 전북 소4048 | 등록연월일: 2022. 11. 24 | 제호: Music<br>\r\n");
      out.write("			발행: C team | 발행소: 전라북도 전주시 덕진구 금암동 이젠컴퓨터학원 4층 407호<br> Music의\r\n");
      out.write("			콘텐츠는 저작권법의 보호를 받으므로, 무단 전재, 복사, 배포 등을 금합니다.<br>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
