/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-10-12 10:59:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import lol.vo.*;
import lol.dbms.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/user/../include/maintail.jsp", Long.valueOf(1664262340236L));
    _jspx_dependants.put("/user/../include/mainhead.jsp", Long.valueOf(1664866248836L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("lol.vo");
    _jspx_imports_packages.add("lol.dbms");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");

UserVO loginvo = (UserVO)session.getAttribute("login");


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"EUC-KR\">\r\n");
      out.write("		<title>League of Legend Inven</title>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"../css/style.css\"/>	\r\n");
      out.write("		<script src=\"../js/jquery-3.6.0.js\"></script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("	<script>\r\n");
      out.write("		");

		if(loginvo != null)
		{
			
      out.write("\r\n");
      out.write("			function DoModify()\r\n");
      out.write("			{\r\n");
      out.write("				window.open(\"../user/uinfomodify.jsp?uno=\" +'");
      out.print( loginvo.getUno()  );
      out.write("' , \"_uinfomodify\",\r\n");
      out.write("				\"width=538,height=360,left=700,top=400\");	\r\n");
      out.write("			}\r\n");
      out.write("			");

		}
		
      out.write("\r\n");
      out.write("		");

		if(loginvo != null)
		{
			
      out.write("\r\n");
      out.write("			function DoQuit()\r\n");
      out.write("			{\r\n");
      out.write("				window.open(\"../user/uquitcheck.jsp?uno=\"+");
      out.print( loginvo.getUno() );
      out.write(", \"_uquitcheck\",\r\n");
      out.write("				\"width=500,height=200,left=800,top=500\");	\r\n");
      out.write("			}\r\n");
      out.write("			");

		}
		
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("		<table  width=\"900px\" align=\"center\" style=\"border-collapse :collapse;\" >\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">\r\n");
      out.write("					<a href=\"../main/index.jsp\">\r\n");
      out.write("					<div style=\"display:block;\">\r\n");
      out.write("					<img src=\"../img/lol1.png\" width=\"800\" height=\"200\" align=\"middle\" style=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<table  border=\"0\" width=\"1200px\" align=\"center\" style=\"border-collapse :collapse;\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"3\" style=\"text-align:right;\">\r\n");
      out.write("				<div class=\"topmenu\" style=\"height:32px;padding-top:10px;\">\r\n");
      out.write("					");

					if(loginvo == null)
					{
						
      out.write("\r\n");
      out.write("						<a href=\"../user/join.jsp\">회원가입</a>\r\n");
      out.write("						<a href=\"../user/login.jsp\">로그인</a>\r\n");
      out.write("						");
 
					}else
					{
						
      out.write("\r\n");
      out.write("						<span>");
      out.print( loginvo.getUname() );
      out.write("</span>님 반갑습니다!\r\n");
      out.write("						<a href=\"../user/logout.jsp\">로그아웃</a>\r\n");
      out.write("						<a href=\"javascript:DoModify();\">회원정보수정</a>\r\n");
      out.write("						<a href=\"javascript:DoQuit();\">회원탈퇴</a>	\r\n");
      out.write("						&nbsp;&nbsp;\r\n");
      out.write("						");
 
					}
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"leftmenu\" style=\"width:200px;\" valign=\"top\">\r\n");
      out.write("						<a href=\"../main/index.jsp\">홈</a>\r\n");
      out.write("						<br>\r\n");
      out.write("						<a href=\"../champion/cplist.jsp\">챔피언 목록</a>\r\n");
      out.write("						<br>\r\n");
      out.write("						<a href=\"../champion/cpreview.jsp\">챔피언 평가</a>		\r\n");
      out.write("						<br>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td valign=\"top\">");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var isCheckID = false;\r\n");
      out.write("var IsUseID = false;\r\n");
      out.write("\r\n");
      out.write("window.onload = function()\r\n");
      out.write("{\r\n");
      out.write("	$(\"#id\").focus();\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function DoUseID()\r\n");
      out.write("{	\r\n");
      out.write("	id = $(\"#id\").val();\r\n");
      out.write("	if(id.length <= 5)\r\n");
      out.write("	{\r\n");
      out.write("		$(\"#msg\").css(\"color\",\"red\");\r\n");
      out.write("		$(\"#msg\").html(\"5~12자 이내로 입력하세요\");\r\n");
      out.write("		IsUseID = false;\r\n");
      out.write("	}else if(id.length >= 12)\r\n");
      out.write("	{\r\n");
      out.write("		$(\"#msg\").css(\"color\",\"red\");\r\n");
      out.write("		$(\"#msg\").html(\"5~12자 이내로 입력하세요\");\r\n");
      out.write("		IsUseID = false;\r\n");
      out.write("	}else\r\n");
      out.write("	{\r\n");
      out.write("		$(\"#msg\").css(\"color\",\"green\");\r\n");
      out.write("		$(\"#msg\").html(\"조건에 맞는 아이디입니다.\");\r\n");
      out.write("		IsUseID = true;\r\n");
      out.write("	}	\r\n");
      out.write("}\r\n");
      out.write("function DoKey()\r\n");
      out.write("{\r\n");
      out.write("	var num1 = document.getElementById(\"num1\").value.length;\r\n");
      out.write("	if(num1 == 3)\r\n");
      out.write("	{\r\n");
      out.write("		$(\"#num2\").focus();\r\n");
      out.write("	}	\r\n");
      out.write("	var num2 = document.getElementById(\"num2\").value.length;\r\n");
      out.write("	if(num2 == 4)\r\n");
      out.write("	{\r\n");
      out.write("		$(\"#num3\").focus();\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function IDCheck()\r\n");
      out.write("{\r\n");
      out.write("	if(IsUseID == false)\r\n");
      out.write("	{\r\n");
      out.write("		alert(\"글자 수가 맞지 않습니다.!\");\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var uid = $(\"#id\").val();\r\n");
      out.write("	if(uid == \"\")\r\n");
      out.write("	{\r\n");
      out.write("		alert(\"아이디를 입력하세요\");\r\n");
      out.write("		$(\"#id\").focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}	\r\n");
      out.write("	window.open(\"idcheck.jsp?id=\"+uid,\"_idcheck\", \"width=500,height=500\");\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function DoUsePW()\r\n");
      out.write("{\r\n");
      out.write("	pw = $(\"#pw\").val();\r\n");
      out.write("	pwcheck = $(\"#pwcheck\").val();\r\n");
      out.write("	if(pwcheck != pw)\r\n");
      out.write("	{\r\n");
      out.write("		$(\"#pwmsg\").css(\"color\",\"red\");\r\n");
      out.write("		$(\"#pwmsg\").html(\"비밀번호가 일치하지 않습니다\");\r\n");
      out.write("	}else\r\n");
      out.write("	{\r\n");
      out.write("		$(\"#pwmsg\").css(\"color\",\"green\");\r\n");
      out.write("		$(\"#pwmsg\").html(\"비밀번호가 일치합니다\");\r\n");
      out.write("	}	\r\n");
      out.write("}\r\n");
      out.write("function DoCheck()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("	//document.join.id.value -> $(\"#id\").val() 이거랑 같음. \r\n");
      out.write("	id = $(\"#id\").val();\r\n");
      out.write("	if(id == \"\") //아이디가 비어있는지 체크\r\n");
      out.write("	{\r\n");
      out.write("		alert(\"아이디를 입력 해주세요\");\r\n");
      out.write("		$(\"#id\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}	\r\n");
      out.write("	if(isCheckID == false) // 중복검사를 실시했는지 체크!\r\n");
      out.write("	{\r\n");
      out.write("		alert(\"아이디 중복검사를 해주세요\");\r\n");
      out.write("		$(\"#id\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}	\r\n");
      out.write("	\r\n");
      out.write("	pw = $(\"#pw\").val();\r\n");
      out.write("	if(pw == \"\") // 비밀번호 비어있는지 체크\r\n");
      out.write("	{\r\n");
      out.write("		alert(\"비밀번호를 입력 해주세요\");\r\n");
      out.write("		$(\"#pw\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	pwcheck = $(\"#pwcheck\").val();\r\n");
      out.write("	if(pwcheck != pw) //비밀번호랑 확인비밀번호랑 같은지 체크\r\n");
      out.write("	{\r\n");
      out.write("		alert(\"비밀번호가 일치하지 않습니다\");\r\n");
      out.write("		$(\"#pwcheck\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}	\r\n");
      out.write("	\r\n");
      out.write("	if($(\"#nickname\").val() == \"\") //닉네임 비어있는지 체크\r\n");
      out.write("	{\r\n");
      out.write("		alert(\"닉네임을 입력 해주세요\");\r\n");
      out.write("		$(\"#nickname\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}	\r\n");
      out.write("	\r\n");
      out.write("	if($(\"#name\").val() == \"\") // 이름이 비었는지 체크\r\n");
      out.write("	{\r\n");
      out.write("		alert(\"이름을 입력 해주세요\");\r\n");
      out.write("		$(\"#name\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}	\r\n");
      out.write("	if($(\"#num1\").val() == \"\" || $(\"#num2\").val() == \"\" || $(\"#num3\").val() == \"\") // 폰번호 비어있는지 체크\r\n");
      out.write("	{\r\n");
      out.write("		alert(\"휴대폰번호를 입력 해주세요\");\r\n");
      out.write("		$(\"#num1\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}	\r\n");
      out.write("	if($(\"#mail1\").val() == \"\" || $(\"#mail2\").val() == \"\") // 메일 비어있는지 체크\r\n");
      out.write("	{\r\n");
      out.write("		alert(\"이메일을을 입력 해주세요\");\r\n");
      out.write("		$(\"#mail1\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}	\r\n");
      out.write("	if(confirm(\"회원가입을 하시겠습니까?\") != 1 ) // 회원가입 할건지 물어보는!\r\n");
      out.write("	{\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("		$(\"#join\").submit();\r\n");
      out.write("		return true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 컨텐츠 출력 되는곳 -------------------------- -->\r\n");
      out.write("<form method=\"post\" id=\"join\" action=\"joinok.jsp\">\r\n");
      out.write("	<table border=\"center\" align=\"center\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th colspan=\"2\" align=\"center\">회원가입</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>*아이디:</td>\r\n");
      out.write("			<td><input type=\"text\" id=\"id\" name=\"id\" onkeyup=\"DoUseID();\"><input type=\"button\" value=\"아이디 중복검사\" onclick=\"IDCheck();\">\r\n");
      out.write("			<span id=\"msg\" style=\"color:red;\">5~12자 이내로 입력하세요</span></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>*비밀번호:</td>\r\n");
      out.write("			<td><input type=\"password\" id=\"pw\" name=\"pw\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>*비밀번호확인:</td>\r\n");
      out.write("			<td><input type=\"password\" id=\"pwcheck\" name=\"pwcheck\" onkeyup=\"DoUsePW();\">\r\n");
      out.write("			<span id=\"pwmsg\"></span></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>*닉네임:</td>\r\n");
      out.write("			<td><input type=\"text\" id=\"nickname\" name=\"nickname\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>*이름:</td>\r\n");
      out.write("			<td><input type=\"text\" id=\"name\" name=\"name\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>*휴대폰 번호:</td>\r\n");
      out.write("			<td><input type=\"text\" id=\"num1\" name=\"num1\" onkeyup=\"DoKey();\" \r\n");
      out.write("			oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\" />\r\n");
      out.write("			-<input type=\"text\" id=\"num2\" name=\"num2\" onkeyup=\"DoKey();\"  oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\" />\r\n");
      out.write("			-<input type=\"text\"id=\"num3\" name=\"num3\" maxlength=\"4\"  oninput=\"this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\\..*)\\./g, '$1');\" /></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>*이메일:</td>\r\n");
      out.write("			<td><input type=\"text\" id=\"mail1\" name=\"mail1\">@<input type=\"text\" id=\"mail2\" name=\"mail2\" placeholder=\"직접입력\">\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"2\" align=\"center\">\r\n");
      out.write("			<input type=\"checkbox\" id=\"agree_MAIL\" name=\"agree_MAIL\" value=\"Y\">메일수신동의&nbsp;\r\n");
      out.write("			<input type=\"checkbox\" id=\"agree_SMS\" name=\"agree_SMS\" value=\"Y\">SMS동의\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<table border=\"0\" align=\"center\" width=\"350px\">\r\n");
      out.write("		<tr class=\"joinbutton\">\r\n");
      out.write("			<td width=\"40%\" align=\"center\"><a href=\"javascript:DoCheck();\">회원가입</a></td>\r\n");
      out.write("			\r\n");
      out.write("			<td width=\"40%\" align=\"center\"><a href=\"../main/index.jsp\">취소</a></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</form>\r\n");
      out.write("<!-- 컨텐츠 출력 되는곳 -------------------------- -->\r\n");
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>		\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
