/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-10-12 05:19:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.champion;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import lol.vo.*;
import lol.dbms.*;

public final class cpinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/champion/../include/../include/mainhead.jsp", Long.valueOf(1664866248836L));
    _jspx_dependants.put("/champion/../include/cphead.jsp", Long.valueOf(1665120752888L));
    _jspx_dependants.put("/champion/../include/cptail.jsp", Long.valueOf(1664262340235L));
    _jspx_dependants.put("/champion/../include/../include/maintail.jsp", Long.valueOf(1664262340236L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("lol.vo");
    _jspx_imports_packages.add("lol.dbms");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");

UserVO loginvo = (UserVO)session.getAttribute("login");


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"EUC-KR\">\r\n");
      out.write("		<title>League of Legend Inven</title>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"../css/style.css\"/>	\r\n");
      out.write("		<script src=\"../js/jquery-3.6.0.js\"></script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("	<script>\r\n");
      out.write("		");

		if(loginvo != null)
		{
			
      out.write("\r\n");
      out.write("			function DoModify()\r\n");
      out.write("			{\r\n");
      out.write("				window.open(\"../user/uinfomodify.jsp?uno=\" +'");
      out.print( loginvo.getUno()  );
      out.write("' , \"_uinfomodify\",\r\n");
      out.write("				\"width=538,height=360,left=700,top=400\");	\r\n");
      out.write("			}\r\n");
      out.write("			");

		}
		
      out.write("\r\n");
      out.write("		");

		if(loginvo != null)
		{
			
      out.write("\r\n");
      out.write("			function DoQuit()\r\n");
      out.write("			{\r\n");
      out.write("				window.open(\"../user/uquitcheck.jsp?uno=\"+");
      out.print( loginvo.getUno() );
      out.write(", \"_uquitcheck\",\r\n");
      out.write("				\"width=500,height=200,left=800,top=500\");	\r\n");
      out.write("			}\r\n");
      out.write("			");

		}
		
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("		<table  width=\"900px\" align=\"center\" style=\"border-collapse :collapse;\" >\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">\r\n");
      out.write("					<a href=\"../main/index.jsp\">\r\n");
      out.write("					<div style=\"display:block;\">\r\n");
      out.write("					<img src=\"../img/lol1.png\" width=\"800\" height=\"200\" align=\"middle\" style=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<table  border=\"0\" width=\"1200px\" align=\"center\" style=\"border-collapse :collapse;\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"3\" style=\"text-align:right;\">\r\n");
      out.write("				<div class=\"topmenu\" style=\"height:32px;padding-top:10px;\">\r\n");
      out.write("					");

					if(loginvo == null)
					{
						
      out.write("\r\n");
      out.write("						<a href=\"../user/join.jsp\">회원가입</a>\r\n");
      out.write("						<a href=\"../user/login.jsp\">로그인</a>\r\n");
      out.write("						");
 
					}else
					{
						
      out.write("\r\n");
      out.write("						<span>");
      out.print( loginvo.getUname() );
      out.write("</span>님 반갑습니다!\r\n");
      out.write("						<a href=\"../user/logout.jsp\">로그아웃</a>\r\n");
      out.write("						<a href=\"javascript:DoModify();\">회원정보수정</a>\r\n");
      out.write("						<a href=\"javascript:DoQuit();\">회원탈퇴</a>	\r\n");
      out.write("						&nbsp;&nbsp;\r\n");
      out.write("						");
 
					}
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"leftmenu\" style=\"width:200px;\" valign=\"top\">\r\n");
      out.write("						<a href=\"../main/index.jsp\">홈</a>\r\n");
      out.write("						<br>\r\n");
      out.write("						<a href=\"../champion/cplist.jsp\">챔피언 목록</a>\r\n");
      out.write("						<br>\r\n");
      out.write("						<a href=\"../champion/cpreview.jsp\">챔피언 평가</a>		\r\n");
      out.write("						<br>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td valign=\"top\">");
      out.write('\r');
      out.write('\n');

String cpno = request.getParameter("cpno");

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function DoReviewModify()\r\n");
      out.write("{\r\n");
      out.write("	window.open(\"../user/reviewmodify.jsp\", \"_reviewmodify\",\r\n");
      out.write("	\"width=500,height=400\");\r\n");
      out.write("}\r\n");
      out.write("function DoCpModify()\r\n");
      out.write("{\r\n");
      out.write("	window.open(\"../admin/cpmodify.jsp?cpno=");
      out.print( cpno );
      out.write("\", \"_cpmodify\",\r\n");
      out.write("	\"width=600,height=550\");\r\n");
      out.write("}\r\n");
      out.write("function DoReviewDelete()\r\n");
      out.write("{\r\n");
      out.write("	if(confirm(\"정말 삭제 하시겠습니까?\") == true)\r\n");
      out.write("	{\r\n");
      out.write("		alert(\"삭제되었습니다.\");\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<table class=\"inner\" border=\"0\" style=\"width:100%;\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>챔피언정보 입니다.</td>\r\n");
      out.write("		<td align=\"right\"><a href=\"javascript:DoCpModify();\">챔피언정보 수정</a></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div class=\"cpinfomenu\">\r\n");
      out.write("	<table border=\"0\" style=\"width:100%;\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td align=\"center\"><a href=\"../champion/cpinfo.jsp\">챔피언 정보</a></td>\r\n");
      out.write("			<td align=\"center\"><a href=\"../champion/cpstory.jsp\">챔피언 스토리</a></td>\r\n");
      out.write("			<td align=\"center\"><a href=\"../champion/cplist.jsp\">챔피언 목록</a></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<!-- 컨텐츠 출력 되는곳 -------------------------- -->\r\n");
      out.write("<!-- 챔피언 컨텐츠 출력 되는 곳 -------------------------- -->\r\n");
      out.write("<div class=\"cpbackground\" style=\"width:1000px; height:400px; margin-left:-1px;\">\r\n");
      out.write("	<table border=\"0\" style=\"width:100%;\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td style=\"width:50px;\"></td>\r\n");
      out.write("			<td rowspan=\"3\" align=\"center\" style=\"width:150px;\"><img src=\"../img/garen_1.jpg\" width=\"80%\"></td>\r\n");
      out.write("			<td style=\"width:50px;\"></td>\r\n");
      out.write("			<td style=\"color:#F6700E;\">가렌, 데마시아의 힘</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td style=\"width:50px;\"></td>\r\n");
      out.write("			<td style=\"width:50px;\"></td>\r\n");
      out.write("			<td style=\"color:#8eb3b8;\">Garen, The Might of Demacia</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<table border=\"0\" style=\"width:100%; \">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>\r\n");
      out.write("			<b>\r\n");
      out.write("			<textarea style=\"width:425px; height:100px; resize:none; padding-left:80px; padding-top:20px;\" readonly>가렌은 고유의 회복 효과로 전투를 오래 지속할 수 있는 챔피언입니다.\r\n");
      out.write("회복 능력은 레벨이 오를수록 강화되어 빠른 속도로 체력을 회복하게 됩니다. 궁극기로는 적에게 고정 피해를 입힐 수 있어 방어력을 무시하고 공격할 수 있습니다.</textarea>\r\n");
      out.write("			</b>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td style=\"color:#F67004; padding-left:80px;\" >포지션 : 전사</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td style=\"color:#F67004; padding-left:80px;\" >평점 : 2</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 챔피언 컨텐츠 출력 되는 곳 -------------------------- -->\r\n");
      out.write("\r\n");
      out.write("<table class=\"inner\" border=\"0\" style=\"width:100%;\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"50px\" align=\"center\">챔피언</td>\r\n");
      out.write("		<td width=\"449px\" align=\"center\">챔피언 평가</td>\r\n");
      out.write("		<td width=\"50px\" align=\"center\">평점</td>\r\n");
      out.write("		<td width=\"118px\" align=\"center\">작성자</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table border=\"0\" style=\"width:100%; margin:5px;\">					\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"45px\" align=\"center\"><img src=\"../img/garen_1.jpg\" width=\"100%\"></td>\r\n");
      out.write("		<td width=\"630px\" align=\"left\" style=\"padding-left:20px;\">가렌에 대한 평가 입니다.</td>\r\n");
      out.write("		<td>평점:2</td>\r\n");
      out.write("		<td width=\"200px\" align=\"center\" colspan=\"2\">작성자<br>&nbsp;&nbsp;&nbsp;2022.10.15 &nbsp;&nbsp;&nbsp;<br>\r\n");
      out.write("		[<a href=\"javascript:DoReviewModify();\">수정</a>] | [<a href=\"javascript:DoReviewDelete();\">삭제</a>]</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"45px\" align=\"center\"><img src=\"../img/garen_1.jpg\" width=\"100%\"></td>\r\n");
      out.write("		<td width=\"630px\" align=\"left\" style=\"padding-left:20px;\">가렌에 대한 평가 입니다.</td>\r\n");
      out.write("		<td width=\"50\">평점:3</td>\r\n");
      out.write("		<td width=\"200px\" align=\"center\" colspan=\"2\">작성자<br>&nbsp;&nbsp;&nbsp;2022.10.15 &nbsp;&nbsp;&nbsp;<br>\r\n");
      out.write("		[<a href=\"javascript:DoReviewModify();\">수정</a>] | [<a href=\"javascript:DoReviewDelete();\">삭제</a>]</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"45px\" align=\"center\"><img src=\"../img/garen_1.jpg\" width=\"100%\"></td>\r\n");
      out.write("		<td width=\"630px\" align=\"left\" style=\"padding-left:20px;\">가렌에 대한 평가 입니다.</td>\r\n");
      out.write("		<td>평점:3</td>\r\n");
      out.write("		<td width=\"200px\" align=\"center\" colspan=\"2\">작성자<br>&nbsp;&nbsp;&nbsp;2022.10.15 &nbsp;&nbsp;&nbsp;<br>\r\n");
      out.write("		[<a href=\"javascript:DoReviewModify();\">수정</a>] | [<a href=\"javascript:DoReviewDelete();\">삭제</a>]</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"80px\">작성자 id</td>\r\n");
      out.write("		<td colspan=\"3\">\r\n");
      out.write("		<input type=\"text\" id=\"cpreivew\" name=\"cpreview\" style=\"width:69%\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("		평점:\r\n");
      out.write("		<select style=\"width:50px\">\r\n");
      out.write("			<option value=\"1\">1</option>\r\n");
      out.write("			<option value=\"2\">2</option>\r\n");
      out.write("			<option value=\"3\">3</option>\r\n");
      out.write("			<option value=\"4\">4</option>\r\n");
      out.write("			<option value=\"5\" selected>5</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("		<a style=\"color:#ffffff; background-color: #060A41; border-radius:3px 3px 3px 3px; padding: 5px 5px;\" href=\"#\">등록</a>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>											\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td align=\"center\" colspan=\"3\">◀ 1 2 3 4 5 6 7 8 9  ▶</td>\r\n");
      out.write("	</tr>								\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>		\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!-- 컨텐츠 출력 되는곳 -------------------------- -->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
