/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-10-12 11:13:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.champion;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import lol.vo.*;
import lol.dbms.*;

public final class cplist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/champion/../include/maintail.jsp", Long.valueOf(1664262340236L));
    _jspx_dependants.put("/champion/../include/mainhead.jsp", Long.valueOf(1664866248836L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("lol.vo");
    _jspx_imports_packages.add("lol.dbms");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");

UserVO loginvo = (UserVO)session.getAttribute("login");


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta charset=\"EUC-KR\">\r\n");
      out.write("		<title>League of Legend Inven</title>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"../css/style.css\"/>	\r\n");
      out.write("		<script src=\"../js/jquery-3.6.0.js\"></script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("	<script>\r\n");
      out.write("		");

		if(loginvo != null)
		{
			
      out.write("\r\n");
      out.write("			function DoModify()\r\n");
      out.write("			{\r\n");
      out.write("				window.open(\"../user/uinfomodify.jsp?uno=\" +'");
      out.print( loginvo.getUno()  );
      out.write("' , \"_uinfomodify\",\r\n");
      out.write("				\"width=538,height=360,left=700,top=400\");	\r\n");
      out.write("			}\r\n");
      out.write("			");

		}
		
      out.write("\r\n");
      out.write("		");

		if(loginvo != null)
		{
			
      out.write("\r\n");
      out.write("			function DoQuit()\r\n");
      out.write("			{\r\n");
      out.write("				window.open(\"../user/uquitcheck.jsp?uno=\"+");
      out.print( loginvo.getUno() );
      out.write(", \"_uquitcheck\",\r\n");
      out.write("				\"width=500,height=200,left=800,top=500\");	\r\n");
      out.write("			}\r\n");
      out.write("			");

		}
		
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("		<table  width=\"900px\" align=\"center\" style=\"border-collapse :collapse;\" >\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"center\">\r\n");
      out.write("					<a href=\"../main/index.jsp\">\r\n");
      out.write("					<div style=\"display:block;\">\r\n");
      out.write("					<img src=\"../img/lol1.png\" width=\"800\" height=\"200\" align=\"middle\" style=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		<table  border=\"0\" width=\"1200px\" align=\"center\" style=\"border-collapse :collapse;\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"3\" style=\"text-align:right;\">\r\n");
      out.write("				<div class=\"topmenu\" style=\"height:32px;padding-top:10px;\">\r\n");
      out.write("					");

					if(loginvo == null)
					{
						
      out.write("\r\n");
      out.write("						<a href=\"../user/join.jsp\">회원가입</a>\r\n");
      out.write("						<a href=\"../user/login.jsp\">로그인</a>\r\n");
      out.write("						");
 
					}else
					{
						
      out.write("\r\n");
      out.write("						<span>");
      out.print( loginvo.getUname() );
      out.write("</span>님 반갑습니다!\r\n");
      out.write("						<a href=\"../user/logout.jsp\">로그아웃</a>\r\n");
      out.write("						<a href=\"javascript:DoModify();\">회원정보수정</a>\r\n");
      out.write("						<a href=\"javascript:DoQuit();\">회원탈퇴</a>	\r\n");
      out.write("						&nbsp;&nbsp;\r\n");
      out.write("						");
 
					}
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"leftmenu\" style=\"width:200px;\" valign=\"top\">\r\n");
      out.write("						<a href=\"../main/index.jsp\">홈</a>\r\n");
      out.write("						<br>\r\n");
      out.write("						<a href=\"../champion/cplist.jsp\">챔피언 목록</a>\r\n");
      out.write("						<br>\r\n");
      out.write("						<a href=\"../champion/cpreview.jsp\">챔피언 평가</a>		\r\n");
      out.write("						<br>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td valign=\"top\">");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("window.onload = function()\r\n");
      out.write("{\r\n");
      out.write("	$(\"#cpdel\").click(function(){\r\n");
      out.write("		var check_val = \"\";\r\n");
      out.write("		$(\"input:checkbox[name='check_cpno']\").each(function()\r\n");
      out.write("		{\r\n");
      out.write("			if(this.checked == true)\r\n");
      out.write("			{\r\n");
      out.write("				if(check_val != \"\") check_val += \",\";\r\n");
      out.write("				check_val += this.value;\r\n");
      out.write("			}	\r\n");
      out.write("		});\r\n");
      out.write("		if(confirm(\"삭제 하시겠습니까?\") == 1)\r\n");
      out.write("		{	\r\n");
      out.write("			window.open(\"../admin/cpdelete.jsp?cpno=\" +check_val, \"_cpdelete\",\r\n");
      out.write("			\"width=600,height=550\");\r\n");
      out.write("		}	\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("function DoCpAdd()\r\n");
      out.write("{\r\n");
      out.write("	window.open(\"../admin/cpadd.jsp\", \"_cpadd\",\r\n");
      out.write("	\"width=600,height=550\");	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("function DoCpDelete()\r\n");
      out.write("{\r\n");
      out.write("	if(confirm(\"삭제하시겠습니까?\") == 1)\r\n");
      out.write("	{\r\n");
      out.write("		window.open(\"../admin/cpdelete.jsp\", \"_cpdelete\",\r\n");
      out.write("		\"width=600,height=550\");	\r\n");
      out.write("		$(\"#cplist\").submit();\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("*/\r\n");
      out.write("//마우스 over시 발동되는 메소드\r\n");
      out.write("function DoDetail(cpno, cpkname, cpename, img, cpinfo)\r\n");
      out.write("{\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : \"get\",\r\n");
      out.write("		url: \"../champion/position.jsp?cpno=\" + cpno,\r\n");
      out.write("		dataType: \"html\",\r\n");
      out.write("		success : function(data)\r\n");
      out.write("		{	\r\n");
      out.write("			//메소드가 실행되면 div가 보여지게함\r\n");
      out.write("			$(\"#cpdetail\").css(\"display\",\"\");\r\n");
      out.write("			// 통신이 성공적으로 이루어졌을때 이 함수를 타게된다.	\r\n");
      out.write("			$(\"#td_cpname\").html(cpkname);\r\n");
      out.write("			$(\"#td_cpename\").html(cpename);\r\n");
      out.write("			$(\"#td_img\").attr(\"src\",\"../upload/\"+img); \r\n");
      out.write("			$(\"#td_info\").html(cpinfo);\r\n");
      out.write("			$(\"#td_position\").html(data);\r\n");
      out.write("			//마우스가 움직일때 따라다니는 코드\r\n");
      out.write("		},\r\n");
      out.write("		error : function(xhr, status, error) \r\n");
      out.write("		{\r\n");
      out.write("			// 통신 오류 발생시\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//마우스가 움직일때 따라다니는 코드\r\n");
      out.write("	$(document).mousemove(\r\n");
      out.write("		function(e) {\r\n");
      out.write("	      mouseX = e.pageX;\r\n");
      out.write("	      mouseY = e.pageY;\r\n");
      out.write("	      $('#cpdetail').css(\"left\", mouseX+15).css(\"top\", mouseY+15);\r\n");
      out.write("	 });\r\n");
      out.write("	\r\n");
      out.write("	//마우스가 떠나면 보이지 않게함.\r\n");
      out.write("	$(this).mouseleave(\r\n");
      out.write("		function()\r\n");
      out.write("		{\r\n");
      out.write("			$(\"#cpdetail\").css(\"display\",\"none\");\r\n");
      out.write("		}		\r\n");
      out.write("	);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 컨텐츠 출력 되는곳 -------------------------- -->\r\n");
      out.write("<table  class=\"inner\" border=\"0\" style=\"width:100%;\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>챔피언 목록입니다.</td>\r\n");
      out.write("		<td align=\"center\"><a href=\"javascript:DoCpAdd();\">챔피언 추가</a></td>\r\n");
      out.write("		<td align=\"center\"><a href=\"#\" id=\"cpdel\">챔피언 삭제</a></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div class= \"inner_a\">\r\n");
      out.write("	<table border=\"0\" style=\"width:100%;\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td><a>역할필터</a></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td align=\"center\">\r\n");
      out.write("			<form id=\"position\" name=\"position\" method=\"post\">\r\n");
      out.write("			<input type=\"checkbox\">&nbsp;&nbsp;전사&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("			<input type=\"checkbox\">&nbsp;&nbsp;마법사&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("			<input type=\"checkbox\">&nbsp;&nbsp;원거리\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td  class=\"search\" align=\"right\">\r\n");
      out.write("			<input type=\"text\" size=\"10\">\r\n");
      out.write("			<a href=\"#\">검색</a>\r\n");
      out.write("			</from>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>	\r\n");
      out.write("	</table>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"divnull\">\r\n");
      out.write("	<br>\r\n");
      out.write("</div>\r\n");
      out.write("	<form method=\"post\" action=\"cpdelete.jsp\" id=\"cplist\" name=\"cplist\"> \r\n");
      out.write("		<table class=\"list_image\" border=\"0\" style=\"width:100%; height:500px\">\r\n");
      out.write("		");

		DBManager db = new DBManager();
		db.DBOpen();
		int rowno = 0;
		String sql = "";
		sql += "select cpno, cpinfo, cpkname, cpename, cpnickname, cpstdimg ";
		sql += "from champion ";
		sql += "order by cpno desc ";
		sql += "limit 0,10 ";
		db.OpenQuery(sql);
		
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("		");
 
			while(db.GetNext() == true)
			{
				String cpno = db.GetValue("cpno");
				String cpinfo = db.GetValue("cpinfo");
				String cpkname = db.GetValue("cpkname");
				String cpename = db.GetValue("cpename");
				String cpnickname = db.GetValue("cpnickname");
				String cpstdimg = db.GetValue("cpstdimg");

					
				if(rowno % 5 == 0)
				{
					
      out.write("\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("					");
 
				}
				
      out.write("\r\n");
      out.write("				<td align=\"center\"><input type=\"checkbox\" id=\"check_cpno\" name=\"check_cpno\" value=\"");
      out.print( cpno );
      out.write("\">\r\n");
      out.write("				<br>\r\n");
      out.write("				<a href=\"cpinfo.jsp?cpno=");
      out.print( cpno );
      out.write("\" onmouseenter=\"DoDetail('");
      out.print( cpno );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( cpkname );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( cpename );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( cpstdimg );
      out.write("', '");
      out.print( cpinfo );
      out.write("');\" id=\"cpimg\">\r\n");
      out.write("				<img src=\"../upload/");
      out.print( cpstdimg );
      out.write("\">\r\n");
      out.write("				</a>\r\n");
      out.write("				<br>\r\n");
      out.write("				<a href=\"cpinfo.jsp?cpno=");
      out.print( cpno );
      out.write('"');
      out.write('>');
      out.print( cpkname );
      out.write("</a>\r\n");
      out.write("				</td>\r\n");
      out.write("				");
 
				rowno++;
			}
			db.DBClose();
			
      out.write("		\r\n");
      out.write("			\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</form>\r\n");
      out.write("<div id=\"cpdetail\" style=\"display:none;\">\r\n");
      out.write("<table border=\"0\" style=\"background-color:black;\">\r\n");
      out.write(" 	<tr>\r\n");
      out.write(" 		<td rowspan=\"3\" style=\"width:30px;\"><img id=\"td_img\" src=\"\"></td>\r\n");
      out.write(" 		<td style=\"color:#F6700E;\" id=\"td_cpname\"></td>\r\n");
      out.write(" 	</tr>\r\n");
      out.write(" 	<tr>\r\n");
      out.write(" 		<td style=\"color:#8eb3b8;\" id=\"td_cpename\"></td>\r\n");
      out.write(" 	</tr>\r\n");
      out.write(" 	<tr>\r\n");
      out.write(" 		<td style=\"color:#7cacbd;\" id=\"td_position\"></td>\r\n");
      out.write(" 	</tr>\r\n");
      out.write(" 	<tr>\r\n");
      out.write(" 		<td colspan=\"2\" style=\"color:#a0acbd;\" id=\"td_info\"></td>\r\n");
      out.write(" 	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 컨텐츠 출력 되는곳 -------------------------- -->\r\n");
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>		\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
